/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/About': RouteRecordInfo<
      '/About',
      '/About',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/login'
      | '/auth/register'
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Home': RouteRecordInfo<
      '/Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Leaderboard': RouteRecordInfo<
      '/Leaderboard',
      '/Leaderboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Playlist/[pid]': RouteRecordInfo<
      '/Playlist/[pid]',
      '/Playlist/:pid',
      { pid: ParamValue<true> },
      { pid: ParamValue<false> },
      | never
    >,
    '/playlist-list': RouteRecordInfo<
      '/playlist-list',
      '/playlist-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user': RouteRecordInfo<
      '/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | '/user/[uid]'
      | '/user/msg'
    >,
    '/user/[uid]': RouteRecordInfo<
      '/user/[uid]',
      '/user/:uid',
      { uid: ParamValue<true> },
      { uid: ParamValue<false> },
      | never
    >,
    '/user/msg': RouteRecordInfo<
      '/user/msg',
      '/user/msg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/video/[vid]': RouteRecordInfo<
      '/video/[vid]',
      '/video/:vid',
      { vid: ParamValue<true> },
      { vid: ParamValue<false> },
      | never
    >,
    '/video-list': RouteRecordInfo<
      '/video-list',
      '/video-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/About.vue': {
      routes:
        | '/About'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/login'
        | '/auth/register'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Home.vue': {
      routes:
        | '/Home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Leaderboard.vue': {
      routes:
        | '/Leaderboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Playlist/[pid].vue': {
      routes:
        | '/Playlist/[pid]'
      views:
        | never
      pathParamNames:
        | 'pid'
    }
    'src/pages/playlist-list.vue': {
      routes:
        | '/playlist-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | '/user'
        | '/user/[uid]'
        | '/user/msg'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/user/[uid].vue': {
      routes:
        | '/user/[uid]'
      views:
        | never
      pathParamNames:
        | 'uid'
    }
    'src/pages/user/msg.vue': {
      routes:
        | '/user/msg'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/video/[vid].vue': {
      routes:
        | '/video/[vid]'
      views:
        | never
      pathParamNames:
        | 'vid'
    }
    'src/pages/video-list.vue': {
      routes:
        | '/video-list'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
